import { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { ArrowRight, BadgeCheck, LockKeyhole, ShieldCheck } from 'lucide-react'
import { useAuth } from '../auth/AuthContext'

async function request(path, body) {
  const response = await fetch(`/api/auth/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw Object.assign(new Error(data.message || 'Something went wrong. Please try again.'), data)
  return data
}

export default function Login() {
  const { signIn } = useAuth(); const nav = useNavigate(); const location = useLocation()
  const [newAccount, setNewAccount] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [otp, setOtp] = useState(''); const [verification, setVerification] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [cooldown, setCooldown] = useState(0)
  const change = event => setForm({ ...form, [event.target.name]: event.target.value })
  useEffect(() => { if (!verification?.resendAt) return; const update = () => setCooldown(Math.max(0, Math.ceil((verification.resendAt - Date.now()) / 1000))); update(); const timer = setInterval(update, 1000); return () => clearInterval(timer) }, [verification?.resendAt])
  const redirect = citizen => { signIn(citizen); nav(location.state?.from || '/report', { replace: true }) }
  const submit = async event => { event.preventDefault(); setError(''); setNotice(''); setBusy(true); try { if (newAccount) { const result = await request('register', form); setVerification({ email: result.email, resendAt: result.resendAt }); setNotice('We sent a six-digit code to your email. It expires in 10 minutes.') } else { const result = await request('login', form); redirect(result.citizen) } } catch (err) { if (err.requiresVerification) setVerification({ email: err.email, resendAt: 0 }); setError(err.message) } finally { setBusy(false) } }
  const verify = async event => { event.preventDefault(); setError(''); setBusy(true); try { const result = await request('verify-email', { email: verification.email, otp }); redirect(result.citizen) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  const resend = async () => { setError(''); setNotice(''); setBusy(true); try { const result = await request('resend-otp', { email: verification.email }); setVerification({ ...verification, resendAt: result.resendAt }); setOtp(''); setNotice('A new code has been sent.') } catch (err) { setError(err.message); if (err.retryAt) setVerification({ ...verification, resendAt: err.retryAt }) } finally { setBusy(false) } }
  const returnToSignIn = () => { setVerification(null); setOtp(''); setError(''); setNotice(''); setNewAccount(false) }
  return <section className="auth-page"><div className="auth-intro"><p className="kicker">CITIZEN ACCESS</p><h1>Your voice, tied to a real citizen account.</h1><p>Verified email keeps every report accountable, makes follow-up possible, and gives you one trusted place to track civic action.</p><div className="trust-list"><p><BadgeCheck size={18}/> Reports are linked to a verified account</p><p><ShieldCheck size={18}/> Updates reach the right person</p><p><LockKeyhole size={18}/> Your details stay private from the public</p></div></div><div className="auth-card"><div className="ticket-strip"/><p className="eyebrow">SECURE PORTAL</p>{verification ? <><h2>Verify your email</h2><p className="muted">Enter the six-digit code sent to <strong>{verification.email}</strong>.</p><form onSubmit={verify}><label>Verification code<input className="otp-input" autoFocus autoComplete="one-time-code" inputMode="numeric" maxLength="6" required value={otp} onChange={event => setOtp(event.target.value.replace(/\D/g, ''))} placeholder="123456" /></label>{error && <p className="form-error">{error}</p>}{notice && <p className="form-notice">{notice}</p>}<button className="button primary full" disabled={busy || otp.length !== 6} type="submit">{busy ? 'Verifying…' : 'Verify email'} <ArrowRight size={17}/></button></form><p className="auth-switch"><button type="button" disabled={busy || cooldown > 0} onClick={resend}>{cooldown ? `Resend code in ${cooldown}s` : 'Resend code'}</button></p><button className="text-button" type="button" onClick={returnToSignIn}>Use a different email</button></> : <><h2>{newAccount ? 'Create your citizen account' : 'Welcome back'}</h2><p className="muted">{newAccount ? 'We’ll verify your email before activating your account.' : 'Sign in to file and track your reports.'}</p><form onSubmit={submit}>{newAccount && <label>Full name<input autoComplete="name" required name="name" value={form.name} onChange={change} placeholder="Your full name" /></label>}<label>Email address<input autoComplete="email" required type="email" name="email" value={form.email} onChange={change} placeholder="you@example.com" /></label><label>Password<input autoComplete={newAccount ? 'new-password' : 'current-password'} required type="password" name="password" value={form.password} onChange={change} placeholder="Minimum 6 characters" /></label>{error && <p className="form-error">{error}</p>}<button className="button primary full" disabled={busy} type="submit">{busy ? 'Please wait…' : newAccount ? 'Create account' : 'Sign in'} <ArrowRight size={17}/></button></form><p className="auth-switch">{newAccount ? 'Already registered?' : 'New to CivicPulse?'} <button type="button" onClick={() => { setNewAccount(!newAccount); setError('') }}>{newAccount ? 'Sign in' : 'Create an account'}</button></p></>}<Link className="quiet-link" to="/">← Return to CivicPulse</Link></div></section>
}
